import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

import { remarkStripFirstH1 } from './plugins/remark-strip-first-h1.mjs';
import { remarkRewriteRepoLinks } from './plugins/remark-rewrite-repo-links.mjs';

// Hosted on GitHub Pages at the custom domain docs.spawnly.run, which serves
// from the root — so we set `site` (canonical URLs + sitemap) but no `base`.
// A `base` would only be needed for a project URL like dbfr3qs.github.io/Spawnly.
// (The apex spawnly.run now serves the dashboard via the EKS ALB.)
export default defineConfig({
  site: 'https://docs.spawnly.run',
  markdown: {
    remarkPlugins: [remarkStripFirstH1, remarkRewriteRepoLinks],
  },
  integrations: [
    starlight({
      title: 'Spawnly Docs',
      description:
        'Authoring and policy documentation for the Spawnly agent platform.',
      customCss: [
        './src/styles/theme.css',
        './src/styles/docs.css',
        './src/styles/demos.css',
        './src/styles/landing.css',
      ],
      sidebar: [
        { slug: 'demos', label: 'See it in action' },
        {
          // Listed explicitly (not autogenerated): the docs are loaded via a
          // glob() from ../docs, and Starlight's `autogenerate` only sees the
          // default src/content/docs path, so it would produce an empty group.
          label: 'Authoring guides',
          items: [
            // Short sidebar labels; pages keep their full frontmatter titles.
            { slug: 'authoring/00-anatomy', label: 'Anatomy of an Agent' },
            { slug: 'authoring/01-job-and-exit', label: '1. Job-and-exit' },
            { slug: 'authoring/02-loop-until-stopped', label: '2. Loop-until-stopped' },
            { slug: 'authoring/03-parent-and-child', label: '3. Parent → child' },
            { slug: 'authoring/04-defining-a-template', label: 'Defining a Template' },
            { slug: 'authoring/05-defining-policy', label: 'Defining Policy' },
            { slug: 'authoring/06-chat', label: 'Chatting with an Agent' },
          ],
        },
        {
          label: 'Concepts',
          items: [
            { slug: 'concepts/organizations', label: 'Organizations (multi-tenancy)' },
          ],
        },
        {
          label: 'Operating',
          items: [
            { slug: 'operating/config-as-code', label: 'Config-as-code with Terraform' },
            { slug: 'operating/remote-agents', label: 'Remote agents (consumer-hosted)' },
          ],
        },
      ],
    }),
  ],
});
