import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

import { remarkStripFirstH1 } from './plugins/remark-strip-first-h1.mjs';
import { remarkRewriteRepoLinks } from './plugins/remark-rewrite-repo-links.mjs';

// Hosted on GitHub Pages at the apex custom domain spawnly.run, which serves
// from the root — so we set `site` (canonical URLs + sitemap) but no `base`.
// A `base` would only be needed for a project URL like dbfr3qs.github.io/Spawnly.
export default defineConfig({
  site: 'https://spawnly.run',
  markdown: {
    remarkPlugins: [remarkStripFirstH1, remarkRewriteRepoLinks],
  },
  integrations: [
    starlight({
      title: 'Spawnly Docs',
      description:
        'Authoring and policy documentation for the Spawnly agent platform.',
      customCss: ['./src/styles/demos.css'],
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/dbfr3qs/Spawnly',
        },
      ],
      sidebar: [
        { slug: 'demos', label: 'See it in action' },
        {
          // Listed explicitly (not autogenerated): the docs are loaded via a
          // glob() from ../docs, and Starlight's `autogenerate` only sees the
          // default src/content/docs path, so it would produce an empty group.
          label: 'Authoring guides',
          items: [
            { slug: 'authoring/00-anatomy' },
            { slug: 'authoring/01-job-and-exit' },
            { slug: 'authoring/02-loop-until-stopped' },
            { slug: 'authoring/03-parent-and-child' },
            { slug: 'authoring/04-defining-a-template' },
            { slug: 'authoring/05-defining-policy' },
            { slug: 'authoring/06-chat' },
          ],
        },
        {
          label: 'Under the hood',
          items: [
            { slug: 'internals/token-minting' },
            { slug: 'internals/spawn-consent' },
          ],
        },
      ],
    }),
  ],
});
